# Generated by Django 2.2.3 on 2019-07-04 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AlugaCarSite', '0002_auto_20190704_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='desricao',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='dataAlugado',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluguel',
            name='diasAluguel',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluguel',
            name='valorPagar',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='disponivel',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.CharField(default='Fiat', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='modelo',
            field=models.CharField(default='Palio', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='valorDia',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
    ]
