# Generated by Django 2.2.3 on 2019-07-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlugaCarSite', '0004_auto_20190704_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='diasAluguel',
            field=models.IntegerField(),
        ),
    ]
