# Generated by Django 2.2.3 on 2019-07-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlugaCarSite', '0005_auto_20190704_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='caminhoFoto',
            field=models.FileField(default='/img/palio.jpeg', upload_to=''),
            preserve_default=False,
        ),
    ]
