# Generated by Django 2.2.3 on 2019-07-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlugaCarSite', '0006_carro_caminhofoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='caminhoFoto',
            field=models.ImageField(blank=True, null=True, upload_to='compra/static/galeria/carros'),
        ),
    ]
