# Generated by Django 2.2.3 on 2019-07-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlugaCarSite', '0009_auto_20190706_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
    ]
