# Generated by Django 2.2.3 on 2019-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlugaCarSite', '0011_auto_20190706_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='dataAlugado',
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='diasAluguel',
            field=models.IntegerField(null=True),
        ),
    ]
